### ISSUE TITLE
Ugly traceback instead of AssertionError

### ISSUE THREAD

**Issue by rockstorm101** [pytest-dev/pytest-mock#131]
Hi, I'm new to testing in python and also new to mock, so I might be doing something wrong that is very obvious. But I fail to see it.

I have the following class in the file `dumb.py`:
```
import os

class Dumb:
    def work_on(self):
        path = os.getcwd()
        return path
```
And the following tests in the file `test_dumb.py`:
```
import pytest
import dumb
import os

def test_one():
    assert False    # "Gracefully" fails with an AssertionError

def test_two(mocker):
    mocker.patch('os.getcwd', side_effect = [1, 2])
    mocked_dumb = dumb.Dumb()
    whatever = mocked_dumb.work_on()   
    os.getcwd.assert_called_once()    # Passes
    assert whatever == 1              # Passes
    whatever2 = mocked_dumb.work_on()
    #assert whatever2 == 1            # Ugly failure
    assert False                      # Ugly failure
    #assert whatever2 == 2            # Passes
```
`test_one` fails with an `AssertionError` as expected, however `test_two` doesn't. The line `assert False` throws the long and unintelligible traceback below. The line `assert whatever2 == 1` also throws a similar terrible traceback, but the line `assert whatever2 == 2` (which evaluates to true in this case) passes. What am I doing wrong? Why am I not getting `AssertionError` on every case?

I'll gladly provide any other outputs
```
$ pytest test_dumb.py -v
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-3.9.3, py-1.7.0, pluggy-0.8.0 -- /home/rock/Projects/test/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/rock/Projects/test, inifile:
plugins: timeout-1.3.2, mock-1.10.0
collected 2 items                                                              

test_dumb.py::test_one FAILED                                            [ 50%]
test_dumb.py::test_two 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/main.py", line 184, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/main.py", line 224, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/main.py", line 245, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/runner.py", line 77, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/runner.py", line 92, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/runner.py", line 174, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/runner.py", line 251, in pytest_runtest_makereport
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/python.py", line 734, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/nodes.py", line 382, in _repr_failure_py
INTERNALERROR>     os.getcwd()
INTERNALERROR>   File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
INTERNALERROR>     return _mock_self._mock_call(*args, **kwargs)
INTERNALERROR>   File "/usr/lib/python3.6/unittest/mock.py", line 998, in _mock_call
INTERNALERROR>     result = next(effect)
INTERNALERROR> StopIteration
Traceback (most recent call last):
  File "/home/rock/Projects/test/venv/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 75, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/main.py", line 217, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/_pytest/main.py", line 207, in wrap_session
    session.startdir.chdir()
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/py/_path/local.py", line 568, in chdir
    old = self.__class__()
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/py/_path/local.py", line 149, in __init__
    self.strpath = py.error.checked_call(os.getcwd)
  File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 998, in _mock_call
    result = next(effect)
StopIteration
```

**Comment by nicoddemus** [comment]
Hi @rockstorm101,

What is happening is that pytest itself needs to call `os.getcwd()`:

```
File "/home/rock/Projects/test/venv/lib/python3.6/site-packages/py/_path/local.py", line 149, in __init__
    self.strpath = py.error.checked_call(os.getcwd)
```

And this fails because of your `os.getcwd()` mocking.

**Comment by rockstorm101** [comment]
Lol. Thanks a lot @nicoddemus. Mystery solved. Does this happen due to something on my configuration? Otherwise, should it be mentioned in the docs? Or should a warning be added? Am I not supposed to mock this function in particular? Are there any other functions which require special care when mocking them?

**Comment by nicoddemus** [comment]
@rockstorm101 we already have a note of care about patching stdlib functions in [the docs](https://docs.pytest.org/en/latest/monkeypatch.html). 👍 

I'm closing this now but feel free to follow up with further questions.

**Comment by blueyed** [comment]
@nicoddemus 
Wasn't there also an issue to improve this in pytest?

**Comment by nicoddemus** [comment]
Hmm I can't find it right now, but feel free to link it here if you do! 😁
