### ISSUE TITLE
0.8.1 incompatible with pytest-qt + pytest-cov on travis

### ISSUE THREAD

**Issue by Sheeo** [pytest-dev/pytest-mock#22]
When both pytest-qt and pytest-cov are installed, none of the py test plugins are picked up by `py.test --fixtures .`

Only happens if all three plugins are loaded. Unclear if this is pytest-mock's fault, pytest-cov, pytest-qt or py.test's fault.

Minimally failing travis build here: https://travis-ci.org/FAForever/server/builds/88285397

Log output:

        $ python --version
        Python 3.5.0
        $ pip --version
        pip 7.1.2 from /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages (python 3.5)
        install
        4.04s$ pip install --use-wheel pytest-mock pytest-qt pytest-cov
        Collecting pytest-mock
          Downloading pytest_mock-0.8.1-py2.py3-none-any.whl
        Collecting pytest-qt
          Downloading pytest_qt-1.8.0-py2.py3-none-any.whl
        Collecting pytest-cov
          Downloading pytest_cov-2.2.0-py2.py3-none-any.whl
        Requirement already satisfied (use --upgrade to upgrade): pytest>=2.4 in /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages (from pytest-mock)
        Collecting coverage>=3.7.1 (from pytest-cov)
          Downloading coverage-4.0.1.tar.gz (349kB)
            100% |████████████████████████████████| 352kB 756kB/s
        Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages (from pytest>=2.4->pytest-mock)
        Building wheels for collected packages: coverage
          Running setup.py bdist_wheel for coverage
          Stored in directory: /home/travis/.cache/pip/wheels/3d/2d/5f/5e812a155cc0752a0f99157ee14aebbcd87b8d425083f463f5
        Successfully built coverage
        Installing collected packages: pytest-mock, pytest-qt, coverage, pytest-cov
        Successfully installed coverage-4.0.1 pytest-cov-2.2.0 pytest-mock-0.8.1 pytest-qt-1.8.0
        0.55s$ py.test --fixtures . | grep mock
        The command "py.test --fixtures . | grep mock" exited with 1.
        Done. Your build exited with 1.

Confirmed working with pytest-mock==0.7

**Comment by Sheeo** [comment]
Cancel that, https://travis-ci.org/FAForever/server/builds/88285865 failed and I have no clue why at this point.

**Comment by The-Compiler** [comment]
If you pass `-rw` to show the pytest warnings, you'll likely get something like this:

```
================= pytest-warning summary =================
WI2 None could not load setuptools entry import: pytest-qt requires either PySide, PyQt4 or PyQt5 to be installed
```

Gladly @nicoddemus is pytest-qt, pytest-mock and pytest maintainer/contributor, so I guess we can still discuss this here :wink:

Some things come to mind:

* Warnings like this one (as compared to deprecation warnings) really should be shown by default, and probably be fatal.
* `pluggy` might need some way to handle `ImportError` for each plugin individually and still load other plugins rather than aborting - /cc @hpk42 
* Maybe `pytest-qt` should raise something other than `ImportError`? But I guess it's still the most appropriate thing...

**Comment by Sheeo** [comment]
Thanks! Indeed what recently happened in the project was a removal of PySide dependency, but `pytest-qt` was mistakenly left in as a dependency.

I concur with your thoughts.

**Comment by nicoddemus** [comment]
> Maybe pytest-qt should raise something other than ImportError?

Arguably raising `RuntimeError` would be appropriate too and would alleviate the problem. What do you guys think?

**Comment by The-Compiler** [comment]
Yeah, why not - how does this look to the user? Will it be shown as an `INTERNALERROR>` or as something more sensible?

**Comment by nicoddemus** [comment]
Instead of a hidden `pytest-warning`, it breaks with a full blown exception:

```
λ py.test foo.py -rw
Traceback (most recent call last):
  File "E:\Miniconda\envs\test-pytesqt\Scripts\py.test-script.py", line 5, in <module>
    sys.exit(main())
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\config.py", line 38, in main
    config = _prepareconfig(args, plugins)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\config.py", line 117, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 264, in __init__
    self.result = func()
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\config.py", line 852, in pytest_cmdline_parse
    self.parse(args)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\config.py", line 957, in parse
    self._preparse(args)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\config.py", line 918, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 501, in load_setuptools_entrypoints
    plugin = ep.load()
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\pkg_resources\__init__.py", line 2312, in load
    return self.resolve()
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\pkg_resources\__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\pytestqt\plugin.py", line 5, in <module>
    from pytestqt.logging import QtLoggingPlugin, _QtMessageCapture, Record
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\pytestqt\logging.py", line 7, in <module>
    from pytestqt.qt_compat import qInstallMsgHandler, qInstallMessageHandler, \
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\pytestqt\qt_compat.py", line 49, in <module>
    QT_API = _guess_qt_api()
  File "E:\Miniconda\envs\test-pytesqt\lib\site-packages\pytestqt\qt_compat.py", line 36, in _guess_qt_api
    raise RuntimeError(msg)
RuntimeError: pytest-qt requires either PySide, PyQt4 or PyQt5 to be installed
```

**Comment by The-Compiler** [comment]
Yeah, why not, let's do that.

**Comment by nicoddemus** [comment]
OK, created an issue for it in pytest-qt: pytest-dev/pytest-qt#109

**Comment by nicoddemus** [comment]
Thanks @Sheeo for bringing this up. :smile:

**Comment by Sheeo** [comment]
You're welcome @nicoddemus, keep up the good work :+1:
