### ISSUE TITLE
[Bug] pytest-sugar fails to print error message when using pytest-mock

### ISSUE THREAD

**Issue by MarcSeebold** [pytest-dev/pytest-mock#253]
pytest-sugar fails to print error message when using pytest-mock

This code

```
import pytest

def test_mock_print(mocker):
    mocker.patch("builtins.print", side_effect=KeyError)
    with pytest.raises(KeyError) as e:
        print("hello there")
    assert str(e) == "this will fail"
```

yields

```
poetry run pytest test.py 
Test session starts (platform: linux, Python 3.7.10, pytest 6.2.4, pytest-sugar 0.9.4)
rootdir: /tmp/tmp.kuvb6cvvBt
plugins: sugar-0.9.4, mock-3.6.1
collecting ... INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/_pytest/runner.py", line 126, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/_pytest/runner.py", line 219, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pytest_sugar.py", line 431, in pytest_runtest_logreport
INTERNALERROR>     print("")
INTERNALERROR>   File "/home/marc/.pyenv/versions/3.7.10/lib/python3.7/unittest/mock.py", line 1016, in __call__
INTERNALERROR>     return _mock_self._mock_call(*args, **kwargs)
INTERNALERROR>   File "/home/marc/.pyenv/versions/3.7.10/lib/python3.7/unittest/mock.py", line 1076, in _mock_call
INTERNALERROR>     raise effect
INTERNALERROR> KeyError


Results (0.03s):
       1 failed
         - test.py:4 test_mock_print
```

In contrast,

```
import pytest


def test_mock_print(mocker):
    #mocker.patch("builtins.print", side_effect=KeyError)
    with pytest.raises(KeyError) as e:
        print("hello there")
        raise KeyError
    assert str(e) == "this works"
```

yields the correct output:

```
poetry run pytest test.py 
Test session starts (platform: linux, Python 3.7.10, pytest 6.2.4, pytest-sugar 0.9.4)
rootdir: /tmp/tmp.kuvb6cvvBt
plugins: sugar-0.9.4, mock-3.6.1
collecting ... 

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_mock_print ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

mocker = <pytest_mock.plugin.MockerFixture object at 0x7f050cc56090>

    def test_mock_print(mocker):
        #mocker.patch("builtins.print", side_effect=KeyError)
        with pytest.raises(KeyError) as e:
            print("hello there")
            raise KeyError
>       assert str(e) == "this works"
E       AssertionError: assert '<ExceptionIn...or() tblen=1>' == 'this works'
E         - this works
E         + <ExceptionInfo KeyError() tblen=1>

test.py:9: AssertionError
----------------------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------------------
hello there

 test.py ⨯                                                                                                                                                                                            100% ██████████
============================================================================================== short test summary info ==============================================================================================
FAILED test.py::test_mock_print - AssertionError: assert '<ExceptionIn...or() tblen=1>' == 'this works'

Results (0.03s):
       1 failed
         - test.py:4 test_mock_print
```

Versions:

```
poetry show
attrs              21.2.0   Classes Without Boilerplate
importlib-metadata 4.6.4    Read metadata from Python packages
iniconfig          1.1.1    iniconfig: brain-dead simple config-ini parsing
packaging          21.0     Core utilities for Python packages
pluggy             0.13.1   plugin and hook calling mechanisms for python
py                 1.10.0   library with cross-python path, ini-parsing, io, code, log facilities
pyparsing          2.4.7    Python parsing module
pytest             6.2.4    pytest: simple powerful testing with Python
pytest-mock        3.6.1    Thin-wrapper around the mock package for easier use with pytest
pytest-sugar       0.9.4    pytest-sugar is a plugin for pytest that changes the default look and feel of pytest (e.g. progressbar, show tests that fail instantly).
termcolor          1.1.0    ANSII Color formatting for output in terminal.
toml               0.10.2   Python Library for Tom's Obvious, Minimal Language
typing-extensions  3.10.0.0 Backported and Experimental Type Hints for Python 3.5+
zipp               3.5.0    Backport of pathlib-compatible object wrapper for zip files
```

```
python --version
Python 3.7.10
```

**Comment by nicoddemus** [comment]
`pytest-sugar` tries to print() something to stdout:

```
INTERNALERROR>   File "/home/marc/.cache/pypoetry/virtualenvs/tmp.kuvb6cvvbt-p5aPtt0W-py3.7/lib/python3.7/site-packages/pytest_sugar.py", line 431, in pytest_runtest_logreport
INTERNALERROR>     print("")
```

But given you have mocked `print` to raise a `KeyError` it fails (as expected).

Nothing can be done by pytest-mock, after all it is correctly mocking `print` to raise an error. However mocking essential builtin functions is bound to break stuff elsewhere, so I would advise caution there.

Closing for now, feel free to follow with further questions.
