### ISSUE TITLE
pytest-mock 0.10.0 fails with an attribute error

### ISSUE THREAD

**Issue by akscram** [pytest-dev/pytest-mock#28]
The new version fails with such problem:
```
Traceback (most recent call last):
  File "/home/ash/git/fuel-octane/.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 80, in wrap_session
    config.do_configure()
  File "/home/ash/git/fuel-octane/.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 621, in do_configure
    self.hook.pytest_configure(config=self)
  File "/home/ash/git/fuel-octane/.tox/py27/local/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/home/ash/git/fuel-octane/.tox/py27/local/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/home/ash/git/fuel-octane/.tox/py27/local/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/home/ash/git/fuel-octane/.tox/py27/local/lib/python2.7/site-packages/pytest_mock.py", line 235, in pytest_configure
    wrap_assert_methods(config)
  File "/home/ash/git/fuel-octane/.tox/py27/local/lib/python2.7/site-packages/pytest_mock.py", line 210, in wrap_assert_methods
    config.add_cleanup(unwrap_assert_methods)
AttributeError: 'Config' object has no attribute 'add_cleanup'
```

pip freeze:

```
Babel==2.2.0
cliff==1.9.0
cmd2==0.6.8
coverage==4.0.3
ecdsa==0.13
flake8==2.2.4
funcsigs==0.4
hacking==0.10.2
iso8601==0.1.11
mccabe==0.2.1
mock==1.3.0
msgpack-python==0.4.7
netaddr==0.7.18
netifaces==0.10.4
oslo.config==1.9.3
oslo.i18n==1.5.0
oslo.serialization==1.4.0
oslo.utils==1.4.0
paramiko==1.13.0
pbr==0.11.1
pep8==1.5.7
prettytable==0.7.2
py==1.4.31
pycrypto==2.6.1
pyflakes==0.8.1
pyparsing==2.0.7
pytest==2.7.3
pytest-cov==2.2.0
pytest-mock==0.10.0
python-fuelclient==7.0.0
python-keystoneclient==1.3.4
pytz==2015.7
PyYAML==3.10
pyzabbix==0.7.3
requests==2.2.1
six==1.9.0
stevedore==1.3.0
wheel==0.24.0
```

**Comment by nicoddemus** [comment]
Hmmm that's a regression for pytest 2.7.X... thanks for noticing.

I'm working on a fix.
